
import javax.swing.JOptionPane;

/*
 * All rights reserved.
 */

/**
 *
 * @author Cowtop
 */
public class CalculatorGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_equation = new javax.swing.JTextField();
        input_value = new javax.swing.JTextField();
        lable_equation = new javax.swing.JLabel();
        lable_value = new javax.swing.JLabel();
        button_clear = new javax.swing.JButton();
        button_calc = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menu_op = new javax.swing.JMenu();
        menu_op_calc = new javax.swing.JMenuItem();
        menu_op_clear = new javax.swing.JMenuItem();
        menu_op_seperator = new javax.swing.JPopupMenu.Separator();
        menu_op_exit = new javax.swing.JMenuItem();
        menu_help = new javax.swing.JMenu();
        menu_help_about = new javax.swing.JMenuItem();
        menu_help_info = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        input_equation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_equationActionPerformed(evt);
            }
        });

        input_value.setEditable(false);

        lable_equation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lable_equation.setText("Enter Equation");

        lable_value.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lable_value.setText("Value");

        button_clear.setText("Clear");
        button_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_clearMouseClicked(evt);
            }
        });

        button_calc.setText("Calculate");

        menu_op.setText("Operations");

        menu_op_calc.setText("Calculate");
        menu_op.add(menu_op_calc);

        menu_op_clear.setText("Clear");
        menu_op_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_op_clearMousePressed(evt);
            }
        });
        menu_op.add(menu_op_clear);
        menu_op.add(menu_op_seperator);

        menu_op_exit.setText("Exit");
        menu_op_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_op_exitMousePressed(evt);
            }
        });
        menu_op.add(menu_op_exit);

        menu.add(menu_op);

        menu_help.setText("Help");

        menu_help_about.setText("About");
        menu_help_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_help_aboutMousePressed(evt);
            }
        });
        menu_help.add(menu_help_about);

        menu_help_info.setText("Information");
        menu_help_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu_help_infoMousePressed(evt);
            }
        });
        menu_help.add(menu_help_info);

        menu.add(menu_help);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_calc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lable_equation, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input_equation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lable_value, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input_value, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_equation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_equation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_value, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lable_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_calc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_equationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_equationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_equationActionPerformed

    private void button_clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_clearMouseClicked
        input_equation.setText("");
        input_value.setText("");
    }//GEN-LAST:event_button_clearMouseClicked

    private void menu_help_infoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_help_infoMousePressed
        JOptionPane.showMessageDialog(this, "Example for input:\n1/2 + 2/3\nNeed space between operands and operation.");
    }//GEN-LAST:event_menu_help_infoMousePressed

    private void menu_help_aboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_help_aboutMousePressed
        JOptionPane.showMessageDialog(this, "Computing Fraction Program");
    }//GEN-LAST:event_menu_help_aboutMousePressed

    private void menu_op_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_op_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_menu_op_exitMousePressed

    private void menu_op_clearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_op_clearMousePressed
        input_equation.setText("");
        input_value.setText("");
    }//GEN-LAST:event_menu_op_clearMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch(ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch(javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_calc;
    private javax.swing.JButton button_clear;
    private javax.swing.JTextField input_equation;
    private javax.swing.JTextField input_value;
    private javax.swing.JLabel lable_equation;
    private javax.swing.JLabel lable_value;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenuItem menu_help_about;
    private javax.swing.JMenuItem menu_help_info;
    private javax.swing.JMenu menu_op;
    private javax.swing.JMenuItem menu_op_calc;
    private javax.swing.JMenuItem menu_op_clear;
    private javax.swing.JMenuItem menu_op_exit;
    private javax.swing.JPopupMenu.Separator menu_op_seperator;
    // End of variables declaration//GEN-END:variables
}
